### ISSUE TITLE
fix 요청

### ISSUE THREAD

**Issue by chojooyoung** [kimdh-hi/kimdh-hi#1]
대현님 안녕하세요 ㅎㅎ 
평소 대현님의 commit들을 유심히 살펴보고, 도움을 받은 적이 많아 항상 감사히 생각하고 있습니다.

다만 대현님 프로필 상단의 github 관리 지표가 다소 의도보다 작게 나오고 있는 것 같아 개인적으로 아쉬워서 수정 요청 이렇게 드립니다.
(의도 하신거라면 셀프 close 하겠습니다 오지랖 죄송합니다..ㅠ)

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/66211721/216245383-7e4826bd-00d8-45cf-a661-65a355b3695b.png">

**Comment by kimdh-hi** [comment]
🙇‍♂️__50%__ 🙇‍♂️

**Comment by chojooyoung** [comment]
ㅎㅎ 훨씬좋네요! 앞으로도 좋은 소식 들려주세요!
